app = "gem"
primary_region = "lhr"

[build]

[http_service]
  internal_port = 9292
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[mounts]
  source="gems"
  destination="/data"
